export const GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST';
export const CLEAR_WEATHER_FORECAST = 'CLEAR_WEATHER_FORECAST';
export const ERROR_WEATHER_FORECAST = 'ERROR_WEATHER_ITEMS_FORECAST';
export const SET_SELECTED_DAY = 'SET_SELECTED_DAY';
export const SET_SELECTED_HOUR = 'SET_SELECTED_HOUR';
export const SET_MENU_VISIBILITY = 'SET_MENU_VISIBILITY';
export const ADD_TO_FAVORITE_CITIES_LIST = 'ADD_TO_FAVORITE_CITIES_LIST';
